 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 workflow_dispatch:
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: davidsonDeCarvalho/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: davidsonDeCarvalho
            # Text on contribution graph 
            text: DAVIDSON
       - uses: davidsonDeCarvalho/simple-push-action@v1
